### ISSUE TITLE
Require 'set' for ruby 2.0

### ISSUE THREAD

**Issue by MichaelXavier** [mbj/vanguard#8]
Sorry for not just doing a pull request but I can't install the gems for development because mutant is behind a private repo for you and was prompting me for a password.

So it looks like in Ruby 2.0, Array#to_set was dropped from array. You have to require 'set' first which monkey patches it back in. You should be able to reproduce this error like so under ruby 2:

```
irb -rvanguard                                                                                                                      rvm:ruby-2.0.0-p247 
/home/eluns/.rvm/gems/ruby-2.0.0-p247/gems/vanguard-0.0.4/lib/vanguard/rule/nullary/attribute/inclusion.rb:36:in `<class:Acceptance>': undefined method `to_set' for ["1", 1, "true", true, "t"]:Array (NoMethodError)
    from /home/eluns/.rvm/gems/ruby-2.0.0-p247/gems/vanguard-0.0.4/lib/vanguard/rule/nullary/attribute/inclusion.rb:34:in `<class:Inclusion>'
    from /home/eluns/.rvm/gems/ruby-2.0.0-p247/gems/vanguard-0.0.4/lib/vanguard/rule/nullary/attribute/inclusion.rb:9:in `<class:Attribute>'
    from /home/eluns/.rvm/gems/ruby-2.0.0-p247/gems/vanguard-0.0.4/lib/vanguard/rule/nullary/attribute/inclusion.rb:6:in `<class:Nullary>'
    from /home/eluns/.rvm/gems/ruby-2.0.0-p247/gems/vanguard-0.0.4/lib/vanguard/rule/nullary/attribute/inclusion.rb:5:in `<class:Rule>'
    from /home/eluns/.rvm/gems/ruby-2.0.0-p247/gems/vanguard-0.0.4/lib/vanguard/rule/nullary/attribute/inclusion.rb:4:in `<module:Vanguard>'
    from /home/eluns/.rvm/gems/ruby-2.0.0-p247/gems/vanguard-0.0.4/lib/vanguard/rule/nullary/attribute/inclusion.rb:3:in `<top (required)>'
    from /home/eluns/.rvm/rubies/ruby-2.0.0-p247/lib/ruby/site_ruby/2.0.0/rubygems/core_ext/kernel_require.rb:64:in `require'
    from /home/eluns/.rvm/rubies/ruby-2.0.0-p247/lib/ruby/site_ruby/2.0.0/rubygems/core_ext/kernel_require.rb:64:in `require'
    from /home/eluns/.rvm/gems/ruby-2.0.0-p247/gems/vanguard-0.0.4/lib/vanguard.rb:82:in `<top (required)>'
    from /home/eluns/.rvm/rubies/ruby-2.0.0-p247/lib/ruby/site_ruby/2.0.0/rubygems/core_ext/kernel_require.rb:116:in `require'
    from /home/eluns/.rvm/rubies/ruby-2.0.0-p247/lib/ruby/site_ruby/2.0.0/rubygems/core_ext/kernel_require.rb:116:in `rescue in require'
    from /home/eluns/.rvm/rubies/ruby-2.0.0-p247/lib/ruby/site_ruby/2.0.0/rubygems/core_ext/kernel_require.rb:122:in `require'
    from /home/eluns/.rvm/rubies/ruby-2.0.0-p247/lib/ruby/2.0.0/irb/init.rb:286:in `block in load_modules'
    from /home/eluns/.rvm/rubies/ruby-2.0.0-p247/lib/ruby/2.0.0/irb/init.rb:284:in `each'
    from /home/eluns/.rvm/rubies/ruby-2.0.0-p247/lib/ruby/2.0.0/irb/init.rb:284:in `load_modules'
    from /home/eluns/.rvm/rubies/ruby-2.0.0-p247/lib/ruby/2.0.0/irb/init.rb:20:in `setup'
    from /home/eluns/.rvm/rubies/ruby-2.0.0-p247/lib/ruby/2.0.0/irb.rb:380:in `start'
    from /home/eluns/.rvm/rubies/ruby-2.0.0-p247/bin/irb:16:in `<main>'
```

The workaround is in the user code to always require set first.

```
irb -rset -rvanguard
```

**Comment by MichaelXavier** [comment]
Whoops. Scratch the part about ruby 2.0. According to the docs, to_set is never on the Array instance to start. You always have to require set to use it.

**Comment by greyblake** [comment]
+1
I faced this also
